### ISSUE TITLE
How do I run this Imao

### ISSUE THREAD

**Issue by venti-latte** [GandyT/Learner#1]

**Comment by venti-latte** [comment]
I have no idea where the exe file is, or how the fuck to run this on discord

**Comment by ASOwnerYT** [comment]
First you need a Discord bot, by going to the [Discord Developer Portal](https://discord.com/developers/applications), click 'New Application', name it, click the 'Bot' tab, click 'Add bot', and bellow 'Token' click 'Copy' (you will need this soon).
Then you need to download [node.js](https://nodejs.org/en/), then download all the files in a ZIP, extract it then run a terminal (command prompt) **in the folder** and run `npm i`. Then you open `config.js` in a text editor such as Notepad, and beside token, in between the quotation marks, paste your bot token from earlier. Then you just go back to the terminal, run `node .` and now the bot should be online! your welcome

**Comment by MenuuTUX** [comment]
lmao, you can't install modules using package lock. _or maybe I did this the hard way or smtg_
Anyways, all I did was create a package.json using "node init" 
after that, you gotta install a tone of modules manually : 
npm i discord.js
npm i @tensorflow-models/universal-sentence-encoder
npm i @tensorflow/tfjs-core
npm i @tensorflow/tfjs-converter
npm i @tensorflow/tfjs-node

That's all the commands, I think you have to add a package.json file for node.js to work.
